import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

const sdkSrc = fileURLToPath(new URL('../skynet-sdk/src/index.ts', import.meta.url));
const sdkCoords = fileURLToPath(new URL('../skynet-sdk/src/coords/index.ts', import.meta.url));
const skyChartMath = fileURLToPath(new URL('../sky-chart/src/math/index.ts', import.meta.url));

export default defineConfig({
  resolve: {
    alias: [
      // skynet-sdk's package.json exports point at `dist/index.js`, which is
      // generated by `npm run build` in that workspace. To keep tests self-
      // contained, resolve straight to the TS source. `./coords` already
      // points at source per its own exports map but we alias both for
      // consistency.
      { find: /^skynet-sdk$/, replacement: sdkSrc },
      { find: /^skynet-sdk\/coords$/, replacement: sdkCoords },
      // @skynet-rtn/sky-chart/math exports map points at TS source already,
      // but vite occasionally trips on the subpath under workspaces. Aliasing
      // here makes resolution deterministic.
      { find: /^@skynet-rtn\/sky-chart\/math$/, replacement: skyChartMath },
    ],
  },
  test: {
    environment: 'node',
    globals: true,
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['node_modules', 'dist'],
  },
});
